version: '3'
services:
  database:
    container_name: database
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: simple
      MYSQL_ROOT_HOST: root
      MYSQL_DATABASE: TEST
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: ./init
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    links:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/TEST?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: simple


#version: '3.0'
#services:
#  database:
#    image: mysql:8
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root_password
#      MYSQL_USER: sa
#      MYSQL_PASSWORD: sa
#      MYSQL_DATABASE: hotplace
#    volumes:
#        - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
#        - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
#  service-a:
#    build: .
#    ports:
#      - "8080:80"
#    links:
#      - database
#    depends_on:
#      - database