version: '3'
services:
  database:
    container_name: database
    image: mysql/mysql-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: simple
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: TEST
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/TEST?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: simple
